BOT_TOKEN: 
  - ODQwNTczNTYwNDIxMzUxNDM0.GlF4XS.YZzJJhc2mocfVt2KczdfeiSaQ6hiZSFQPwbiA4
CHANNEL_ID: 
  - 971488439931392130
  - 1037811694564560966
MODE: custom
REPLY: 
SIMSIMI_LANG: en
DELAY: 1800
DEL_AFTER: 
REPOST_LAST_CHAT: 100