BOT_TOKEN: 
  - ODUyODYwMDA4MjMyMzg2NTkw.GvWdbL.33JF8aSFVHXP-YHdo-maCm_-9rcDbQ8uFC7rlg
CHANNEL_ID: 
  - 1093069619134205963
MODE: custom
REPLY: 
SIMSIMI_LANG: en
DELAY: 1800
DEL_AFTER: 
REPOST_LAST_CHAT: 100
