BOT_TOKEN: 
  - ODUyODYwMDA4MjMyMzg2NTkw.GFXznE.M_RurHkRq3NwL-gak4oxXPdDGv5bubCnw-jTUc
CHANNEL_ID: 
  - 1093069619134205963
MODE: custom
REPLY: 
SIMSIMI_LANG: en
DELAY: 1800
DEL_AFTER: 
REPOST_LAST_CHAT: 100
